### ISSUE TITLE
Make it possible to execute LoadTest by schedule via CronJob

### ISSUE THREAD

**Issue by olegchorny** [verfio/fortio-operator#15]
let's add new field in spec, like
spec:
  schedule: "*/1 * * * *"

**Comment by olegchorny** [comment]
on second thought it seems like CronJob is not the best approach. Let's try to implement this feature via #17

**Comment by olegchorny** [comment]
no need to implement in favor of #17

**Comment by olegchorny** [comment]
closed because it was implemented in #17

**Comment by TenSt** [comment]
Implemented with commit ["crontest ready"](https://github.com/verfio/fortio-operator/commit/263a3e540b35e02427e641f95242dc3ec451d1a8).
