### ISSUE TITLE
LoadTest's Status is not being updated in Kubernetes 1.9

### ISSUE THREAD

**Issue by olegchorny** [verfio/fortio-operator#2]
Expected result: Status field should be updated against any k8s version. 
It works on Kubernetes 1.11 atm.

**Comment by TenSt** [comment]
Fixed with this [commit](https://github.com/verfio/fortio-operator/commit/40da898d54e5db5d03991d4de9b0a46940557ebb). Now Status of both LoadTest and CurlTest is updated in Kubernetes 1.9.
