### ISSUE TITLE
[Design] How to expose results in Prometheus compatible way.

### ISSUE THREAD

**Issue by olegchorny** [verfio/fortio-operator#28]
Design the solution and briefly describe it.

**Comment by olegchorny** [comment]
let's say we have such results. https://fortio.istio.io/data/2017-12-20-231208_Test_local_run_1k_qps.json
We need to expose:
**1) Summary:**
http_request_duration_seconds{quantile="0.5" }  0.0004447198151357597
http_request_duration_seconds{quantile="0.75"}  0.0004880473714615829
http_request_duration_seconds{quantile="0.99"}  0.0011333333333333334
http_request_duration_seconds{quantile="0.999"}  0.0028548387096774216

we'll pull this data from this data set.
"Percentiles": [
      {
        "Percentile": 50,
        "Value": 0.0004447198151357597
      },
      {
        "Percentile": 75,
        "Value": 0.0004880473714615829
      },
      {
        "Percentile": 99,
        "Value": 0.0011333333333333334
      },
      {
        "Percentile": 99.9,
        "Value": 0.0028548387096774216
      }
    ]

**2) Counters**
http_requests_total{method="GET | POST", endpoint="URL", status="200"}
http_requests_total{method="GET | POST", endpoint="URL", status="500"}
...
this data will be obtained from this data set:
 "RetCodes": {
    "200": 30000
  },

This is a good starting point for the exposed data.

**Comment by olegchorny** [comment]
Every time when operator pulls the data from the job/cr, specified metrics should be exposed in prometheus format as 'current data set'. 
Prom scapes this data -> next job produces new results -> operator pulls results and exposes them -> prom scrapes them again.
to expose results we'd need to ListenAndServe inside the Operator and expose the endpoint via k8s Service.
https://prometheus.io/docs/guides/go-application/#adding-your-own-metrics

**Comment by TenSt** [comment]
Done via #30.
