### ISSUE TITLE
Add support of POST method

### ISSUE THREAD

**Issue by olegchorny** [verfio/fortio-operator#8]
from fortio's help: 
 -content-type string
        Sets http content type. Setting this value switches the request method from GET to POST
  -payload string
        Payload string to send along
https://github.com/fortio/fortio

**Comment by TenSt** [comment]
Fixed with this [commit](https://github.com/verfio/fortio-operator/commit/d8b212102ad2e9c14afe4818bf9ac9e4145cbeb9).
