### ISSUE TITLE
Allow the file attachment in case of POST

### ISSUE THREAD

**Issue by olegchorny** [verfio/fortio-operator#9]
From Fortio's help
  -payload-file path
        File path to be use as payload (POST for http), replaces -payload when
https://github.com/fortio/fortio

**Comment by TenSt** [comment]
There is no way doing this using configMaps. Declaring configMap via yaml will be the same as copying content of the file to the yaml.
Here is an example of how configMap declaration look like.
Command: 
`kubectl create configmap test --from-file=/home/stepan_maksimchuk/payload.txt --dry-run --output yaml | tee /home/stepan_maksimchuk/configmap.yaml`
Yaml:
apiVersion: v1
data:
  payload.txt: |
    StartTest
    {"test":"data"}
    EndTest
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test

And here is the yaml of our CR using payload parameter:
apiVersion: fortio.verf.io/v1alpha1
kind: CurlTest
metadata:
  name: verfio
spec:
  url: "https://verf.io"
  lookForString: "VERF.IO"
  method: "POST"
  payload: |
    StartTest
    {"test":"data"}
    EndTest
  maxPayloadSizeKB: "10"

Content of the file should be posted inside payload parameter or new "payloadFile" parameter in the same way. There is no way to create configMap from file using declarative way right now.
Here is the [link](https://github.com/kubernetes/kubernetes/issues/41711) to one of the issues on Kubernetes.
Also, here is an [answer](https://stackoverflow.com/questions/51268488/kubernetes-configmap-set-from-file-in-yaml-configuration) to the same question on StackOverflow.

**Comment by TenSt** [comment]
There might be a way to copy local file to a specific pod, but that would require to use another image for fortio as original fortio image does not have 'tar' executable which is used by "kubectl cp" command and so forth we will need to use something like that.
Don't know if we still want to implement this. Using just "payload" parameter with copying content to is like showed above seems good to me.

**Comment by TenSt** [comment]
Doing via configMaps - there is one scenario when it would be useful: using the same payload file (in configmap) for different tests. Define configMap one time and don't need to copy content of payload file into each test using payload parameter.
Implemented with #18.
